version: '3.8'

services:
  app:
    image: "firaskdidi/projetdevops:${APP_VERSION}"  # Use dynamic version tag
    container_name: app_container
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password # set your MySQL root password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
      - prometheus

  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password # same password as above
      MYSQL_DATABASE: db
    volumes:
      - mysql_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  mysql_data: