name: CI Pipeline

on:
  push:
    branches:
      - Adam_branch
  pull_request:
    branches:
      - Adam_branch

jobs:
  git_clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: Adam_branch
          fetch-depth: 1

      - name: Pull latest changes
        run: git pull origin Adam_branch

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
